### ISSUE TITLE
convert CVTensor back to torch tensor complex

### ISSUE THREAD

**Issue by rachelglenn** [josiahwsmith10/complextorch#4]
Hi. How do I convert a CVTensor back to a torch tensor complex tensor? Is it possible to do this in between model layers or would the casting cause an error with the gradient? Thank you in advance.

**Comment by josiahwsmith10** [comment]
You can do x.complex(), which should retain the gradients.

**Comment by rachelglenn** [comment]
Thank you. I will close this issue. I have another issue with the gradient. I will open an new issue.
